bot_token: 'token'
owner_id: ['275312272975462411']
description: 'idk what to put here lol'
command_prefix: '>os.'
default_status: 'use >os.help for a list of commands'
discord_bots_key: 'key'
carbon_key: 'key'
twitch_key: 'key'
youtube_key: 'key'
osu_key: 'key'
dev_server: 'https://discord.gg/123456'

user_agent: 'User-Agent/1.0.0 (Comment like link to site)'
extensions: [cogs.cog1, cogs.cog2]

shard_count: 1
shard_id: 0

db_host: 'localhost'
db_name: 'Bot_Name'
db_cert: 'cert.pem'
db_port: 28015
db_user: 'admin'
db_pass: 'password'